[package]
name = "hello-world"
version = "0.1.0"

[addresses]
system = "0x1"
program = "0xb2b2c3069734e5c7efa8507028d07d618b2e4640601a752fe82febe22f2fec58"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"
